image: node:lts-jessie-slim

before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client rsync -y )
    - mkdir -p ~/.ssh && chmod 700 ${HOME}/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ${HOME}/.ssh/id_rsa
    - chmod 600 ${HOME}/.ssh/id_rsa 
    - ssh-add ${HOME}/.ssh/id_rsa

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: Production
    url: https://arieh.de/youtube-timer
  script: 
    # - npm install
    # - npm run build
    - rsync -hrvz --delete --exclude=_ -e 'ssh -o StrictHostKeyChecking=no' ./ ariehci@ordorbles.uk:~/youtube-cooking-timer
    - ssh -t ariehci@ordorbles.uk "cd ~/youtube-cooking-timer && npm install && npm run build"
  only:
    - master